// <auto-generated />
namespace KUMA_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class 增加支援的自動增加識別碼的屬性再一次1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(增加支援的自動增加識別碼的屬性再一次1));
        
        string IMigrationMetadata.Id
        {
            get { return "201907270518402_增加支援的自動增加識別碼的屬性再一次1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
