// <auto-generated />
namespace KUMA_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class 刪除唯一識別值 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(刪除唯一識別值));
        
        string IMigrationMetadata.Id
        {
            get { return "201907270521526_刪除唯一識別值"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
