// <auto-generated />
namespace KUMA_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class 更改支援的支援標題欄位屬性 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(更改支援的支援標題欄位屬性));
        
        string IMigrationMetadata.Id
        {
            get { return "201907270731399_更改支援的支援標題欄位屬性"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
