// <auto-generated />
namespace KUMA_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class User_AddLineImgUrl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_AddLineImgUrl));
        
        string IMigrationMetadata.Id
        {
            get { return "201907281321051_User_AddLineImgUrl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
