// <auto-generated />
namespace KUMA_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Shippers加入Fare : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Shippers加入Fare));
        
        string IMigrationMetadata.Id
        {
            get { return "201907222213255_Shippers加入Fare"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
