// <auto-generated />
namespace KUMA_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class 再試試3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(再試試3));
        
        string IMigrationMetadata.Id
        {
            get { return "201907270717062_再試試3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
