// <auto-generated />
namespace KUMA_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class order增加運費欄位1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(order增加運費欄位1));
        
        string IMigrationMetadata.Id
        {
            get { return "201907231305390_order增加運費欄位1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
